// Code generated by protoc-gen-go.
// source: HadoopIPCRPC.proto
// DO NOT EDIT!

package hadoop_common

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type IpcRpcRequestHeaderProto struct {
	IpcConnectionContext *IpcConnectionContextProto `protobuf:"bytes,1,opt,name=ipcConnectionContext" json:"ipcConnectionContext,omitempty"`
	RpcRequestHeader     *RpcRequestHeaderProto     `protobuf:"bytes,2,opt,name=rpcRequestHeader" json:"rpcRequestHeader,omitempty"`
	XXX_unrecognized     []byte                     `json:"-"`
}

func (m *IpcRpcRequestHeaderProto) Reset()         { *m = IpcRpcRequestHeaderProto{} }
func (m *IpcRpcRequestHeaderProto) String() string { return proto.CompactTextString(m) }
func (*IpcRpcRequestHeaderProto) ProtoMessage()    {}

func (m *IpcRpcRequestHeaderProto) GetIpcConnectionContext() *IpcConnectionContextProto {
	if m != nil {
		return m.IpcConnectionContext
	}
	return nil
}

func (m *IpcRpcRequestHeaderProto) GetRpcRequestHeader() *RpcRequestHeaderProto {
	if m != nil {
		return m.RpcRequestHeader
	}
	return nil
}

func init() {
}
